# render.yaml
services:
  - type: web
    name: automation-bot
    env: node
    buildCommand: |
      npm install
      cd api && npm install && npm run build
      cd ../web && npm install && npm run build  
      cd ../worker && npm install && npx playwright install chromium && npm run build
    startCommand: node start-all.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000