# render.yaml
services:
  - type: web
    name: automation-bot
    env: node
    buildCommand: npm install
    startCommand: node start-all.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000